---
version: '3'
services:
  web:
    image: ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_WEB}:${TAG}
    ports:
      - 8443:8443
    logging:
      driver: awslogs
      options:
        awslogs-group: ${LOG_GROUP}
        awslogs-region: ${REGION}
        awslogs-stream-prefix: web
  api:
    image: ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_API}:${TAG}
    ports:
      - 8090:8090
    logging:
      driver: awslogs
      options:
        awslogs-group: ${LOG_GROUP}
        awslogs-region: ${REGION}
        awslogs-stream-prefix: api
    environment:
      CACHE_ENGINE: ${CACHE_ENGINE}
      CACHE_ENDPOINT: ${CACHE_ENDPOINT}
  back:
    image: ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO_BACK}:${TAG}
    ports:
      - 7080:7080
    logging:
      driver: awslogs
      options:
        awslogs-group: ${LOG_GROUP}
        awslogs-region: ${REGION}
        awslogs-stream-prefix: back
    environment:
      DB_ENGINE: ${DB_ENGINE}
      DB_NAME: ${DB_NAME}
      DB_ENDPOINT: ${DB_ENDPOINT}
